// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/

int party_bonus_system_enable;
int party_bonus_same_map_minimum;
int refine_pass_system_enable;
int charm_refine_enable;	// Charm Refine
int pet_refine_enable;	// Pet Refine
